add_newline = false

format = '''
â•­â”€-\[ ($username)@($hostname) \]--\[ ($directory)\]$status $git_branch$git_status
â•°â”€-> 
'''

[line_break]
disabled = true

[character]
use_symbol_for_status = true
success_symbol = "[>](bold green)"
error_symbol = "[âœ—](bold red)"

[username]
disabled = false
show_always = true
style_user = "bold yellow"
format = "[$user]($style)"

[hostname]
ssh_only = false
disabled = false
style = "bold red"
format = "[$hostname]($style)"

[directory]
truncation_length = 7
truncation_symbol = "â€¦/"
truncate_to_repo = true
style = "bold blue"

[status]
style = "red"
symbol = "ğŸ’¥"
format = '--[\[$symbol$status\]]($style)'
disabled = false

[git_branch]
symbol = "ğŸŒ± "

[git_status]
ahead = "â‡¡ğŸğŸ’¨${count}"
diverged = "â‡•â‡¡ğŸ˜µ${ahead_count}â‡£${behind_count}"
behind = "â‡£ğŸ˜°${count}"
conflicted = "ğŸ³"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[cmd_duration]
disabled = true

